name: Override environment variables
on: workflow_dispatch
env:
  EXAMPLE: Define by workflow level
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${EXAMPLE}"
      - env:
          EXAMPLE: Defined by step level
        run: echo "${EXAMPLE}"